version: '3'

services:
  db:
    image: mysql:9.0.1-oracle
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    container_name: aula-virtual-backend
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: